app = "ws-service-anhminh"

primary_region = "sin"

[build]
  image = "anhminh123/ws-gateway:latest"

[env]
  PORT = "3006"

[[services]]
  internal_port = 3006
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
