app = "ws-gateway-anhminh"
primary_region = "sin"

[build]
  image = "anhminh123/ws-gateway:latest"

[env]
  PORT = "3006"

[[services]]
  internal_port = 3006
  protocol = "tcp"
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 3006
    handlers = []

  [[services.ports]]
    port = 5006   
    handlers = []

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
