version: '3.8'

services:
  api-gateway:
    image: anhminh123/api-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - apps/api-gateway/.env
    depends_on:
      - user-service
      - patient-service
      - imaging-service
      - system-service
    networks:
      - dicom-network
    restart: unless-stopped

  user-service:
    image: anhminh123/user-service:${TAG:-latest}
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
    ports:
      - "5002:5002"
    env_file:
      - apps/user-service/.env
    networks:
      - dicom-network
    restart: unless-stopped

  imaging-service:
    image: anhminh123/imaging-service:${TAG:-latest}
    build:
      context: .
      dockerfile: apps/imaging-service/Dockerfile
    ports:
      - "5003:5003"
    env_file:
      - apps/imaging-service/.env
    networks:
      - dicom-network
    restart: unless-stopped

  patient-service:
    image: anhminh123/patient-service:${TAG:-latest}
    build:
      context: .
      dockerfile: apps/patient-service/Dockerfile
    ports:
      - "5004:5004"
    env_file:
      - apps/patient-service/.env
    networks:
      - dicom-network
    restart: unless-stopped

  system-service:
    image: anhminh123/system-service:${TAG:-latest}
    build:
      context: .
      dockerfile: apps/system-service/Dockerfile
    ports:
      - "5005:5005"
    env_file:
      - apps/system-service/.env
    networks:
      - dicom-network
    restart: unless-stopped

  ws-service:
    image: anhminh123/ws-gateway:${TAG:-latest}
    build:
      context: .
      dockerfile: apps/ws-gateway/Dockerfile
    ports:
      - "3006:3006"
      - "5006:5006"
    env_file:
      - apps/ws-gateway/.env
    networks:
      - dicom-network
    restart: unless-stopped

networks:
  dicom-network:
    driver: bridge
