# fly.toml app configuration file generated for user-service-dicom on 2025-12-05T20:54:54+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'user-service-dicom2'
primary_region = 'sin'

[build]
dockerfile = './Dockerfile'


[[services]]
internal_port = 5002
protocol = "tcp"
auto_stop_machines = "off"
auto_start_machines = true
min_machines_running = 1
[services.concurrency]
type = "connections"
hard_limit = 100
soft_limit = 80


[[vm]]
size = 'shared-cpu-1x'
