app = "user-service-anhminh"

primary_region = "sin"

[build]
  image = "anhminh123/user-service:latest"

[env]
  PORT = "5002"

[[services]]
  internal_port = 5002
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
