app = "api-gateway-anhminh"

primary_region = "sin"

[build]
  image = "anhminh123/api-gateway:latest"

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
