app = "system-service-anhminh"
primary_region = "sin"

[build]
  image = "anhminh123/system-service:latest"

[env]
  PORT = "5005"

[[services]]
  internal_port = 5005
  protocol = "tcp"
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 5005
    handlers = []

  [services.concurrency]
    type = "connections"
    soft_limit = 25
    hard_limit = 50

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"