app = "system-service-anhminh"

primary_region = "sin"

[build]
  image = "anhminh123/system-service:latest"

[env]
  PORT = "5005"

[[services]]
  internal_port = 5005
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
