name: DICOM_BE CI/CD

on:
  push:
    branches: ["main", "quang", "test"] # branch phụ để test docker image
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "apps/backend/package-lock.json" # ✅ Chỉ định đúng path

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          cd apps/backend
          npm ci

      # 4️⃣ Build NestJS services (dùng Nx)
      - name: Build NestJS services
        run: |
          cd apps/backend
          npx nx run-many --target=build

      # 5️⃣ Build Docker images
      - name: Build Docker image for user-service
        run: |
          cd apps/backend
          docker build -t dicom/user-service:latest    -f apps/user-service/Dockerfile .

      - name: Build Docker image for patient-service
        run: |
          cd apps/backend
          docker build -t dicom/patient-service:latest -f apps/patient-service/Dockerfile .

      - name: Build Docker image for imaging-service
        run: |
          cd apps/backend
          docker build -t dicom/imaging-service:latest -f apps/imaging-service/Dockerfile .\

      - name: Build Docker image for system-service
        run: |
          cd apps/backend
          docker build -t dicom/system-service:latest -f apps/system-service/Dockerfile .

      - name: Build Docker image for api-gateway
        run: |
          cd apps/backend
          docker build -t dicom/api-gateway:latest -f apps/api-gateway/Dockerfile .

      # # 6️⃣ Login Docker Hub
      # - name: Docker Hub Login
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASS }}

      # # 7️⃣ Push Docker images
      # - name: Push Docker images
      #   run: |
      #     docker push dicom/user-service:latest
      #     docker push dicom/patient-service:latest
      #     docker push dicom/imaging-service:latest

      # # 8️⃣ Deploy lên server qua SSH
      # - name: Deploy to Server
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       cd /app/dicom-be
      #       docker compose pull
      #       docker compose up -d
